# main.py
import ultraimport

#This adds `file2` to the `autogenerated` package as a side effect.
Stuff = ultraimport('__dir__/autogenerated/file2.py', 'OtherStuff', package='autogenerated')

#In `file1`, we try to import `file2`. Luckly we had added it to the autogenerated package above.
from autogenerated.file1 import Stuff

print(Stuff)
